package com.vitorsantos.barbearia_api.enums;

/**
 * Códigos de erro que o front pode usar para identificar o problema
 * programaticamente, sem depender do texto da mensagem (que pode mudar).
 */
public enum ErrorCode {
  TELEFONE_DUPLICADO,
  NOME_SERVICO_DUPLICADO,
  CLIENTE_NAO_ENCONTRADO,
  BARBEIRO_NAO_ENCONTRADO,
  SERVICO_NAO_ENCONTRADO,
  AGENDAMENTO_NAO_ENCONTRADO,
  RECURSO_NAO_ENCONTRADO,
  BARBEIRO_INATIVO,
  SERVICO_INATIVO,
  CLIENTE_JA_NA_FILA,
  CLIENTE_COM_ATENDIMENTO_ATIVO,
  BARBEIRO_COM_FILA_ATIVA,
  BARBEIRO_OCUPADO,
  FILA_VAZIA,
  FORA_DA_ORDEM_DA_FILA,
  TRANSICAO_STATUS_INVALIDA,
  CONFIRMACAO_INVALIDA,
  CONFLITO_CONCORRENCIA,
  VIOLACAO_INTEGRIDADE,
  SENHA_INCORRETA,
  MUITAS_TENTATIVAS,
  ERRO_VALIDACAO,
  REQUISICAO_INVALIDA,
  METODO_NAO_PERMITIDO,
  ERRO_INTERNO
}
